"""Upgrade

Revision ID: 98a238533b3e
Revises: 50829fd5a201
Create Date: 2024-11-11 14:55:03.720181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a238533b3e'
down_revision: Union[str, None] = '50829fd5a201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.String(), nullable=True))
    op.drop_index('ix_users_slung', table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.drop_column('users', 'slung')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slung', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index('ix_users_slung', 'users', ['slung'], unique=1)
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###
